# Generated by Django 5.2.4 on 2025-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='passing_score',
            field=models.IntegerField(default=50),
        ),
    ]
